### ISSUE TITLE
The game states get request failed.

### ISSUE THREAD

**Issue by Lord-Funion** [ProdigyPNP/P-NP#26]
(node:2411) UnhandledPromiseRejectionWarning: Error: The game status request failed.
    at /snapshot/P-NP/dist/index.js:37:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `P-NP --trace-warnings ...` to show where the warning was created)
(node:2411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by afkvido** [comment]
Hi,
P-NP is legacy code that isn't maintained anymore. Sorry.

**Comment by ProdigyOrigin** [comment]
## Hacks have moved

# New Prodigy mods at [extension.prodigyorigin.com](https://extension.prodigyorigin.com)
